@file:Suppress("UnstableApiUsage", "KDocMissingDocumentation", "ObjectPropertyName", "RemoveRedundantBackticks", "UnusedImport", "UsePropertyAccessSyntax", "SpellCheckingInspection") // Suppresses various lint warnings for the build file

import java.io.ByteArrayOutputStream // Imports the ByteArrayOutputStream class to handle byte array output.

plugins { // Block for applying Gradle plugins.
    alias(libs.plugins.android.application) // Applies the Android application plugin.
    alias(libs.plugins.kotlin.android) // Applies the Kotlin Android plugin.
    alias(libs.plugins.google.gms.google.services) // Applies the Google Services plugin for Firebase.
    id("kotlin-parcelize")
    alias(libs.plugins.google.firebase.appdistribution) // Applies the Kotlin Parcelize plugin for boilerplate-free Parcelable implementation.
}

android { // Block for Android specific configurations.
    namespace = "com.ayushcodes.blogapp" // Sets the namespace for the application's generated R and BuildConfig classes.
    compileSdk = 36 // Sets the Android SDK version to compile against.

    defaultConfig { // Block for default configurations applied to all build variants.
        applicationId = "com.ayushcodes.blogapp" // Sets the unique application ID for publishing.
        minSdk = 24 // Sets the minimum Android API level required to run the app.
        targetSdk = 36 // Sets the target Android API level for the app.
        versionCode = 1 // Sets the version code, an integer that increases with each release.
        versionName = "1.0" // Sets the version name, a string for display to users.

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner" // Configures the test runner for Android instrumented tests.
    }

    buildTypes { // Block for configuring different build types (e.g., debug, release).
        release { // Configures the 'release' build type.
            isMinifyEnabled = false // Disables code shrinking and obfuscation for the release build.
            proguardFiles( // Specifies the ProGuard configuration files.
                getDefaultProguardFile("proguard-android-optimize.txt"), // Includes the default ProGuard rules from the Android SDK.
                "proguard-rules.pro" // Includes the project-specific ProGuard rules.
            )
        }
    }
    compileOptions { // Block for Java compiler options.
        sourceCompatibility = JavaVersion.VERSION_11 // Sets the Java language version for the source code.
        targetCompatibility = JavaVersion.VERSION_11 // Sets the Java language version for the generated bytecode.
    }
    kotlinOptions { // Block for Kotlin compiler options.
        jvmTarget = "11" // Sets the JVM version for the Kotlin compiler.
    }
    buildFeatures{ // Block for enabling/disabling build features.
        viewBinding = true // Enables the View Binding feature to easily access views.
    }
}

dependencies { // Block for declaring project dependencies.

    // ANDROIDX LIBRARIES
    implementation(libs.androidx.core.ktx) // Provides essential Kotlin extensions for Android development.
    implementation(libs.androidx.appcompat) // Enables use of modern Android APIs on older Android versions.
    implementation(libs.material) // A set of UI components for implementing Material Design.
    implementation(libs.androidx.activity) // Manages activity lifecycle and provides components like OnBackPressedDispatcher.
    implementation(libs.androidx.constraintlayout) // A flexible layout manager for creating responsive UIs.
    implementation(libs.androidx.cardview) // A UI component for creating card-based layouts.
    implementation(libs.androidx.credentials) // Simplifies user sign-in and credential management.
    implementation(libs.androidx.credentials.play.services.auth) // Integrates Credential Manager with Google Play Services for sign-in.
    implementation(libs.androidx.recyclerview) // Efficiently displays large lists of data.

    // LIFECYCLE EXTENSIONS (Added for ViewModel and repeatOnLifecycle support)
    implementation(libs.androidx.lifecycle.viewmodel.ktx) // Provides ViewModel lifecycle-aware components with Kotlin extensions.
    implementation(libs.androidx.lifecycle.runtime.ktx) // Provides lifecycle runtime components with Kotlin extensions.
    implementation(libs.androidx.activity.ktx) // Provides Activity Kotlin extensions.
    implementation(libs.androidx.fragment.ktx) // Provides Fragment Kotlin extensions.

    // CIRCLE IMAGE VIEW
    implementation(libs.circleimageview) // Library for displaying images in a circular shape.

    // FIREBASE LIBRARIES
    implementation(libs.firebase.analytics) // Provides Google Analytics for Firebase to track user engagement.
    implementation(libs.firebase.database) // A real-time NoSQL database for syncing data across clients.
    implementation(libs.firebase.storage) // Provides cloud storage for user-generated content like images and videos.
    implementation(libs.firebase.firestore) // A scalable NoSQL cloud database for storing and syncing data.
    implementation(libs.firebase.auth) // Provides services to authenticate and manage users.

    // GOOGLE SERVICES
    implementation(libs.googleid) // Provides APIs for Google Sign-In and other identity services.
    implementation(libs.play.services.auth) // Provides access to Google authentication services.

    // TESTING LIBRARIES
    testImplementation(libs.junit) // A popular framework for writing unit tests in Java.
    androidTestImplementation(libs.androidx.junit) // Provides Android-specific extensions for JUnit tests.
    androidTestImplementation(libs.androidx.espresso.core) // A UI testing framework for writing automated tests.

    // CUSTOM SWEET ALERT DIALOGUE
    implementation(libs.sweetalert) // A library for creating beautiful and interactive alert dialogs.

    // FANCY TOAST
    implementation(libs.fancytoast) // A library for creating custom and visually appealing toast messages.

    // GLIDE LIBRARY
    implementation(libs.glide) // A powerful image loading and caching library for Android.
}
